### ISSUE TITLE
Installation/usage guide

### ISSUE THREAD

**Issue by HamidShojanazeri** [tmbdev/tarp#3]
I am trying to use tarp in [splitting video tutorial for webdataset](https://github.com/tmbdev/webdataset/blob/master/docs/ytsamples-split.ipynb) and was wondering if there is any installation/setup guide. Thanks.

**Comment by wooters** [comment]
Here are the steps I used to install `tarp` on Ubuntu 18.04:

First, install go according to https://golang.org/doc/install if you don't already have it.

Then:
```bash
git clone https://github.com/tmbdev/tarp.git
cd tarp
make bin/tarp
sudo make install
```

**Comment by tmbdev** [comment]
Sorry, I didn't bother documenting this since it's a standard Golang program. You can use the Makefile.  You can also install it with standard Golang tools:

    $ go get github.com/tmbdev/tarp/tarp

**Comment by mickaelseznec** [comment]
> Sorry, I didn't bother documenting this since it's a standard Golang program. You can use the Makefile. You can also install it with standard Golang tools:
> 
> ```
> $ go get github.com/tmbdev/tarp/tarp
> ```

Hi! README.md says `go get github.com/tmbdev/tarp` instead. The confusion may originate from this typo. You might want to fix it there.

**Comment by kdonbekci** [comment]
Also, running the the `go get -v` command today produces the following error output. 
```
github.com/dgraph-io/badger (download)
cannot find package "github.com/dgraph-io/badger/v2" in any of:
	/usr/local/go/src/github.com/dgraph-io/badger/v2 (from $GOROOT)
	/home/username/go/src/github.com/dgraph-io/badger/v2 (from $GOPATH)
```
The src folder for badger seems to no longer have a folder called `v2` that `tarp` was referencing.

**Comment by tmbdev** [comment]
@mickaelseznec 

```
$ go get github.com/tmbdev/tarp/tarp
```

seems to work for me. Are you still having problems?

**Comment by tmbdev** [comment]
@kdonbekci I believe `go get` will interpret the /v2 at the end as a Github version tag, so there won't be any such subdirectory. The `tarp` command install fine the way it is for me. If you want to check out the Badger source code corresponding to it, just check out the latest "v2..." or "v3..." release tag from Github.
